# Generated by Django 5.1.3 on 2024-11-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semd',
            name='name',
        ),
        migrations.AddField(
            model_name='semd',
            name='lid',
            field=models.CharField(blank=True, max_length=255, verbose_name='Локальный идентификатор документа'),
        ),
        migrations.AddField(
            model_name='semd',
            name='otd',
            field=models.CharField(default='', max_length=255, verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='semd',
            name='personal',
            field=models.CharField(default='', max_length=255, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='semd',
            name='reg_error',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='semd',
            name='status',
            field=models.CharField(default='', max_length=255, verbose_name='Статус передачи'),
        ),
        migrations.AddField(
            model_name='semd',
            name='vid_semd',
            field=models.CharField(default='', max_length=255, verbose_name='Вид СЭМДа'),
        ),
    ]
