# Generated by Django 5.1.3 on 2025-03-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_semd_name_semd_lid_semd_otd_semd_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semd',
            name='semd_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
