# Generated by Django 5.1.3 on 2025-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_semd_semd_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='semd',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Месяц'),
        ),
    ]
