# Generated by Django 5.1.3 on 2025-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_semd_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='semd',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
